### PR TITLE
Fix to build HttpResponseException when charset is malformed

### LINKED ISSUE #323: IllegalCharsetNameException in HttpResponse getContentCharset() if charset is malformed
> Fatal Exception: java.lang.RuntimeException: An error occured while executing doInBackground()
>        at android.os.AsyncTask$3.done(AsyncTask.java:304)
>        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
>        at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
>        at java.util.concurrent.FutureTask.run(FutureTask.java:242)
>        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
>        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
>        at java.lang.Thread.run(Thread.java:818)
> Caused by java.nio.charset.IllegalCharsetNameException: %s
>        at java.nio.charset.Charset.checkCharsetName(Charset.java:197)
>        at java.nio.charset.Charset.forName(Charset.java:295)
>        at com.google.api.client.http.HttpMediaType.getCharsetParameter(HttpMediaType.java:321)
>        at com.google.api.client.http.HttpResponse.getContentCharset(HttpResponse.java:526)
>        at com.google.api.client.http.HttpResponse.parseAsString(HttpResponse.java:516)
>        at com.google.api.client.http.HttpResponseException$Builder.(HttpResponseException.java)
>        at com.google.api.client.http.HttpResponseException.(HttpResponseException.java)
>        at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1061)

The place where this occurs is in HttpMediaType, which does not enforce valid parameter to be passed to Charset.forName()

``` java
  /**
   * Returns the specified charset or {@code null} if unset.
   */
  public Charset getCharsetParameter() {
    String value = getParameter("charset");
    return value == null ? null : Charset.forName(value);
  }
```

### PR DESCRIPTION
**Pull request by ajaaym**
Fixes #323 IllegalCharsetNameException in HttpResponse getContentCharset() if charset is malformed

- [ ] Tests pass
- [ ] Appropriate docs were updated (if necessary)

### CODE REVIEW

File: google-http-client/src/main/java/com/google/api/client/http/HttpResponseException.java [hunk 1]
```diff
@@ -176,9 +177,11 @@ public Builder(HttpResponse response) {
         if (content.length() == 0) {
           content = null;
         }
-      } catch (IOException exception) {
+      } catch (IOException  exception) {
```
Comment (chingor13) [inline google-http-client/src/main/java/com/google/api/client/http/HttpResponseException.java]: Looks like some extra whitespace was added.

**Comment by ajaaym** [comment]
@chingor13 added test case. please take a look.
