### PR TITLE
fix: UriTemplate reserved expansion does not escape reserved chars

### LINKED ISSUE #1838: UriTemplate reserved expansion should not escape reserved characters
UriTemplate.expand should not escape reserved characters in values for reserved expansion (e.g., templates of the form "{+var}").

According to section of [3.2.3  Reserved Expansion: {+var}](https://www.rfc-editor.org/rfc/rfc6570#section-3.2.3), reserved character should not be escaped.
Level 2 templates add the plus ("+") operator, for expansion of values that are allowed to include reserved URI characters ([Section 1.5](https://www.rfc-editor.org/rfc/rfc6570#section-1.5)).

Example code:

``` java
    @Test
    public void testExpandTemplates_reservedExpansion_shouldNotEscapeReservedCharSet() {

        var genDelims = ":/?#[]@";
        var subDelims = "!$&'()*+,;=";
        var reservedSet = genDelims+subDelims;

        var requestMap = Map.of("var", reservedSet);

        assertThat(UriTemplate.expand("{+var}", requestMap, false), is(reservedSet));

        // Expected: is ":/?#[]@!$&'()*+,;="
        //     but: was ":/?%23%5B%5D@!$&'()*+,;="
        
    }
```

### PR DESCRIPTION
**Pull request by cHengstler**
When using UriTemplate.expand with a reserved expansion "{+var}", a set of allowed characters must not  be encoded. According to section of [3.2.3  Reserved Expansion: {+var}](https://www.rfc-editor.org/rfc/rfc6570#section-3.2.3), unreserved and reserved character should not be escaped.

This fix adds the missing characters `#[]` that must not be percent encoded when using reserved expansion.

- [x] Ensure the tests and linter pass
- [x] Code coverage does not decrease (if any source code was changed)
- [x] Appropriate docs were updated (if necessary)

Fixes #1838

### CODE REVIEW

**Comment by suztomo** [comment]
Memo:

1. Are the added characters (`#[]`) marked as the reserved set? Yes
   ```
     reserved       =  gen-delims / sub-delims
     gen-delims     =  ":" / "/" / "?" / "#" / "[" / "]" / "@"
   ```

1. (Todo on me) Try out this change in java-storage before merge, and see any failures.

**Comment by cHengstler** [comment]
Hi @suztomo,

thanks for reviewing, linting issues should be solved now.

File: google-http-client/src/test/java/com/google/api/client/http/UriTemplateTest.java [hunk 1]
```diff
@@ -322,4 +322,30 @@ public void testExpandSeveralTemplatesNoParametersUsed() {
...
+
+    String unReservedSet = "-._~";
+
+    SortedMap<String, Object> requestMap = Maps.newTreeMap();
+    requestMap.put("var", unReservedSet);
+
+    assertEquals(
+        "Reserved expansion must not escape chars from unreserved set according to rfc6570#section-3.2.3",
+        unReservedSet,
+        UriTemplate.expand("{+var}", requestMap, false));
```
Comment (suztomo) [inline google-http-client/src/test/java/com/google/api/client/http/UriTemplateTest.java:349]: Memo: Python's uritemplate agrees:

```
>>> a="-._~"; a == URITemplate("{+var}").expand(var=a)
True
>>> a=":/?#[]@!$&'()*+,;="; a == URITemplate("{+var}").expand(var=a)
True
```

**Review by suztomo — APPROVED** [review]
