### PR TITLE
fix: default application/json charset to utf-8

### LINKED ISSUE #1102: the default charset incorrect when the content-type is application/json
## Environment details

1.  HTTP Requests with the "content-type: applications/json" response
2. OS type and version: All
3. Java version: All
4. google-http-client version(s): All

#### Steps to reproduce

  1. A Server response "content-type: application/json" with some special characters like Chinese.
  2. From the https://tools.ietf.org/html/rfc4627, 3.Encoding "JSON text SHALL be encoded in Unicode.  The default encoding is  UTF-8."
  3. But in google-http-java-client/google-http-client/src/main/java/com/google/api/client/http/HttpResponse.java, it use the charset Charsets.ISO_8859_1.

Thanks!

### PR DESCRIPTION
**Pull request by chingor13**
Fixes #1102

### CODE REVIEW

File: google-http-client/src/main/java/com/google/api/client/http/HttpResponse.java [hunk 1]
```diff
@@ -512,8 +514,18 @@ public String parseAsString() throws IOException {
...
+    if (mediaType != null) {
+      // use specified charset parameter from content/type header if available
+      if (mediaType.getCharsetParameter() != null) {
+        return mediaType.getCharsetParameter();
+      }
+      // fallback to well-known charsets
+      if (mediaType.getType().equals("application") && mediaType.getSubType().equals("json")) {
+        // https://tools.ietf.org/html/rfc4627 - JSON must be encoded with UTF-8
+        return StandardCharsets.UTF_8;
+      }
```
Comment (chingor13) [inline google-http-client/src/main/java/com/google/api/client/http/HttpResponse.java:526]: Fallback code can be refactored if we want to add more defaults.

File: google-http-client/src/main/java/com/google/api/client/http/HttpResponse.java [hunk 2]
```diff
@@ -512,8 +514,18 @@ public String parseAsString() throws IOException {
...
-    return mediaType == null || mediaType.getCharsetParameter() == null
-        ? StandardCharsets.ISO_8859_1
-        : mediaType.getCharsetParameter();
+    if (mediaType != null) {
+      // use specified charset parameter from content/type header if available
+      if (mediaType.getCharsetParameter() != null) {
+        return mediaType.getCharsetParameter();
+      }
+      // fallback to well-known charsets
+      if (mediaType.getType().equals("application") && mediaType.getSubType().equals("json")) {
```
Comment (elharo) [inline google-http-client/src/main/java/com/google/api/client/http/HttpResponse.java:523]: possible null pointer exception here; invert

Comment (chingor13) [reply google-http-client/src/main/java/com/google/api/client/http/HttpResponse.java]: Done.

**Review by elharo — APPROVED** [review]
