### PR TITLE
Fix broken snapshot and proto tests

### LINKED ISSUE #509: HttpRequestTest.testExecute failing at HEAD
Results :

Failed tests: 
  HttpRequestTest.testExecute_curlLogger:1199 expected:<...P-Java-Client/1.26.0[-SNAPSHOT] (gzip)' -- 'http://...> but was:<...P-Java-Client/1.26.0[] (gzip)' -- 'http://...>
  HttpRequestTest.testExecute_curlLoggerWithContentEncoding:1230 expected:<...P-Java-Client/1.26.0[-SNAPSHOT] (gzip)' -H 'Content...> but was:<...P-Java-Client/1.26.0[] (gzip)' -H 'Content...>
  HttpRequestTest.testExecute_headerSerialization:961 expected:<[foo Google-HTTP-Java-Client/1.26.0-SNAPSHOT (gzip)]> but was:<[foo Google-HTTP-Java-Client/1.26.0 (gzip)]>
  HttpRequestTest.testSuppressUserAgentSuffix:1111 expected:<...P-Java-Client/1.26.0[-SNAPSHOT] (gzip)> but was:<...P-Java-Client/1.26.0[] (gzip)>
  HttpRequestTest.testUserAgentWithExecuteErrorAndIOExceptionHandler:630 expected:<...P-Java-Client/1.26.0[-SNAPSHOT] (gzip)> but was:<...P-Java-Client/1.26.0[] (gzip)>
  HttpRequestTest.testUserAgentWithExecuteErrorAndRetryEnabled:614 expected:<...P-Java-Client/1.26.0[-SNAPSHOT] (gzip)> but was:<...P-Java-Client/1.26.0[] (gzip)>

Tests run: 308, Failures: 6, Errors: 0, Skipped: 0

### LINKED ISSUE #514: ProtocolBuffersTest doesn't compile
```
Running com.google.api.client.protobuf.ProtocolBuffersTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.039 sec <<< FAILURE! - in com.google.api.client.protobuf.ProtocolBuffersTest
testParseAndClose(com.google.api.client.protobuf.ProtocolBuffersTest)  Time elapsed: 0.011 sec  <<< ERROR!
java.lang.Error: 
Unresolved compilation problems: 
	SimpleProto cannot be resolved to a type
	SimpleProto cannot be resolved
	SimpleProto cannot be resolved to a variable
	SimpleProto cannot be resolved to a type
	Bound mismatch: The generic method parseAndClose(InputStream, Class<T>) of type ProtocolBuffers is not applicable for the arguments (ByteArrayInputStream, Class<TestMessage>). The inferred type TestMessage is not a valid substitute for the bounded parameter <T extends MessageLite>
	SimpleProto cannot be resolved to a type

	at com.google.api.client.protobuf.ProtocolBuffersTest.testParseAndClose(ProtocolBuffersTest.java:28)

```

### PR DESCRIPTION
**Pull request by elharo**
@chingor13 
fix #509 
fix #514

### CODE REVIEW

File: google-http-client/src/test/java/com/google/api/client/http/HttpRequestTest.java [hunk 1]
```diff
@@ -1197,7 +1198,8 @@ public void testExecute_curlLogger() throws Exception {
       if (message.startsWith("curl")) {
         found = true;
         assertEquals("curl -v --compressed -H 'Accept-Encoding: gzip' -H 'User-Agent: "
-            + HttpRequest.USER_AGENT_SUFFIX + "' -- 'http://google.com/#q=a'\"'\"'b'\"'\"'c'",
+            + "Google-HTTP-Java-Client/" + HttpRequest.VERSION + " (gzip)"
```
Comment (chingor13) [inline google-http-client/src/test/java/com/google/api/client/http/HttpRequestTest.java]: Aren't these already equivalent?

https://github.com/googleapis/google-http-java-client/blob/master/google-http-client/src/main/java/com/google/api/client/http/HttpRequest.java#L65
