### PR TITLE
fix: HttpResponse GZip content encoding equality change

### LINKED ISSUE #842: HttpResponse uses contains where it needs equals
```
         if (!returnRawInputStream
              && contentEncoding != null	              && contentEncoding != null
              && contentEncoding.contains("gzip")) {
```

"contains" is incorrect. This should be equals or perhaps equalsIgnoreCase with a trim, or something like that. However it shouldn't fire on foogzipbar.

### PR DESCRIPTION
**Pull request by egsavage**
Fixes #842 by having HttpResponse compare (case insensitive) the content-encoding against "gzip" and "x-gzip" (HTTP 1.1).

### CODE REVIEW

File: google-http-client/src/main/java/com/google/api/client/http/HttpResponse.java [hunk 1]
```diff
@@ -80,6 +80,12 @@
   /** Whether {@link #getContent()} should return raw input stream. */
   private final boolean returnRawInputStream;
 
+  /** Content encoding for GZip */
+  private static final String CONTENT_ENCODING_GZIP = "gzip";
+
+  /** Content encoding for GZip HTTP 1.1 */
+  private static final String CONTENT_ENCODING_XGZIP = "x-gzip";
```
Comment (elharo) [inline google-http-client/src/main/java/com/google/api/client/http/HttpResponse.java]: Neat. Didn't know about this one. For the comment though, this is a legacy value, not the recommended value in HTTP 1.1.

File: google-http-client/src/main/java/com/google/api/client/http/HttpResponse.java [hunk 2]
```diff
@@ -330,7 +336,8 @@ public InputStream getContent() throws IOException {
           String contentEncoding = this.contentEncoding;
           if (!returnRawInputStream
               && contentEncoding != null
-              && contentEncoding.contains("gzip")) {
+              && (CONTENT_ENCODING_GZIP.equalsIgnoreCase(contentEncoding.trim())
```
Comment (elharo) [inline google-http-client/src/main/java/com/google/api/client/http/HttpResponse.java]: equalsIgnoreCase needs a character set; in this context UTF-8 probably works.

File: google-http-client/src/main/java/com/google/api/client/http/HttpResponse.java [hunk 3]
```diff
@@ -330,7 +336,8 @@ public InputStream getContent() throws IOException {
           String contentEncoding = this.contentEncoding;
```
Comment (elharo) [inline google-http-client/src/main/java/com/google/api/client/http/HttpResponse.java]: Existing i\ssue note: I don't see why we copy this into a local variable.

File: google-http-client/src/main/java/com/google/api/client/http/HttpResponse.java (hunk 1 above)
Comment (egsavage) [reply google-http-client/src/main/java/com/google/api/client/http/HttpResponse.java]: Please see latest commit.

File: google-http-client/src/main/java/com/google/api/client/http/HttpResponse.java (hunk 2 above)
Comment (egsavage) [reply google-http-client/src/main/java/com/google/api/client/http/HttpResponse.java]: I'm not sure where your concerns lie since Java Strings are UTF-16. Please advise.

File: google-http-client/src/main/java/com/google/api/client/http/HttpResponse.java (hunk 3 above)
Comment (egsavage) [reply google-http-client/src/main/java/com/google/api/client/http/HttpResponse.java]: Please see the latest commit.

**Comment by egsavage** [comment]
> This needs a test case.

Please see the latest commit.

File: google-http-client/src/main/java/com/google/api/client/http/HttpResponse.java [hunk 4]
```diff
@@ -333,12 +333,12 @@ public InputStream getContent() throws IOException {
...
         try {
           // gzip encoding (wrap content with GZipInputStream)
-          String contentEncoding = this.contentEncoding;
           if (!returnRawInputStream
-              && contentEncoding != null
-              && (CONTENT_ENCODING_GZIP.equalsIgnoreCase(contentEncoding.trim())
-                  || CONTENT_ENCODING_XGZIP.equalsIgnoreCase(contentEncoding.trim()))) {
-            lowLevelResponseContent = new GZIPInputStream(lowLevelResponseContent);
+                  && this.contentEncoding != null
+                  && (CONTENT_ENCODING_GZIP.equalsIgnoreCase(this.contentEncoding.trim())
```
Comment (elharo) [inline google-http-client/src/main/java/com/google/api/client/http/HttpResponse.java]: needs a locale; case transformation depends on locale

File: google-http-client/src/test/java/com/google/api/client/http/HttpResponseTest.java [hunk 5]
```diff
@@ -495,4 +495,30 @@ public LowLevelHttpResponse execute() throws IOException {
...
   }
+
+  public void testGetContent_otherEncodingWithgzipInItsName_GzipIsNotUsed() throws IOException {
+    final MockLowLevelHttpResponse mockResponse = new MockLowLevelHttpResponse();
+    mockResponse.setContent("abcd");
+    mockResponse.setContentEncoding("otherEncodingWithgzipInItsName");
+    mockResponse.setContentType("text/plain");
+
+    HttpTransport transport =
+            new MockHttpTransport() {
```
Comment (elharo) [inline google-http-client/src/test/java/com/google/api/client/http/HttpResponseTest.java]: google style is two space indents with 4 spaces for a continuation line

File: google-http-client/src/main/java/com/google/api/client/http/HttpResponse.java [hunk 6]
```diff
@@ -334,11 +334,11 @@ public InputStream getContent() throws IOException {
         try {
           // gzip encoding (wrap content with GZipInputStream)
           if (!returnRawInputStream
-                  && this.contentEncoding != null
-                  && (CONTENT_ENCODING_GZIP.equalsIgnoreCase(this.contentEncoding.trim())
-                      || CONTENT_ENCODING_XGZIP.equalsIgnoreCase(this.contentEncoding.trim()))) {
+              && this.contentEncoding != null
+              && (CONTENT_ENCODING_GZIP.equals(this.contentEncoding.trim())
```
Comment (elharo) [inline google-http-client/src/main/java/com/google/api/client/http/HttpResponse.java]: I think per spec you need ignore case--correct me if I'm wrong about that--but you need to do it with the right locale, not necessarily the default.

Comment (chingor13) [reply google-http-client/src/main/java/com/google/api/client/http/HttpResponse.java]: The header name is case-insensitive, header values are dependent on which field. For content encoding, valid values are a list of defined tokens [maintained by IANA](http://www.iana.org/assignments/http-parameters/http-parameters.xhtml#content-coding).

Comment (egsavage) [reply google-http-client/src/main/java/com/google/api/client/http/HttpResponse.java]: @elharo , @chingor13 - I have another commit that has case-insensitive checks and hopefully addresses the prior locale issues mentioned. But given the recent point raised by @chingor13 , it seems that only the header NAME should be case-insensitive and not the actual values which I believe the current PR addresses.

Let me know if you'd like me to push the new commit to the branch.

File: google-http-client/src/main/java/com/google/api/client/http/HttpResponse.java [hunk 7]
```diff
@@ -333,12 +334,12 @@ public InputStream getContent() throws IOException {
...
         try {
           // gzip encoding (wrap content with GZipInputStream)
-          if (!returnRawInputStream
-              && this.contentEncoding != null
-              && (CONTENT_ENCODING_GZIP.equals(this.contentEncoding.trim())
-              || CONTENT_ENCODING_XGZIP.equals(this.contentEncoding.trim()))) {
-            lowLevelResponseContent =
-                new ConsumingInputStream(new GZIPInputStream(lowLevelResponseContent));
+          if (!returnRawInputStream && this.contentEncoding != null) {
+            final String oontentEncoding = this.contentEncoding.trim().toLowerCase(Locale.ENGLISH);
```
Comment (elharo) [inline google-http-client/src/main/java/com/google/api/client/http/HttpResponse.java]: google style doesn't use final on local variables except where required;

also oontent --> content

File: google-http-client/src/test/java/com/google/api/client/http/HttpResponseTest.java [hunk 8]
```diff
@@ -461,6 +462,21 @@ public LowLevelHttpResponse execute() throws IOException {
   }
 
   public void testGetContent_gzipEncoding_finishReading() throws IOException {
+    do_testGetContent_gzipEncoding_finishReading("gzip");
+  }
+
+  public void testGetContent_gzipEncoding_finishReadingWithUppercaseContentEncoding() throws IOException {
```
Comment (elharo) [inline google-http-client/src/test/java/com/google/api/client/http/HttpResponseTest.java]: needs `@Test`; writing the test first and making sure it fails helps avoid problems like this

File: google-http-client/src/test/java/com/google/api/client/http/HttpResponseTest.java [hunk 9]
```diff
@@ -461,6 +462,21 @@ public LowLevelHttpResponse execute() throws IOException {
...
+    do_testGetContent_gzipEncoding_finishReading("GZIP");
+  }
+
+  public void testGetContent_gzipEncoding_finishReadingWithDifferentDefaultLocaleAndUppercaseContentEncoding() throws IOException {
```
Comment (elharo) [inline google-http-client/src/test/java/com/google/api/client/http/HttpResponseTest.java]: needs `@Test`;

File: google-http-client/src/test/java/com/google/api/client/http/HttpResponseTest.java [hunk 10]
```diff
@@ -461,6 +462,21 @@ public LowLevelHttpResponse execute() throws IOException {
...
+    Locale originalDefaultLocale = Locale.getDefault();
+    Locale.setDefault(Locale.JAPAN);
+    do_testGetContent_gzipEncoding_finishReading("GZIP");
+    Locale.setDefault(originalDefaultLocale);
+  }
+
+  private void do_testGetContent_gzipEncoding_finishReading(String contentEncoding) throws IOException {
     byte[] dataToCompress = "abcd".getBytes(StandardCharsets.UTF_8);
     byte[] mockBytes;
```
Comment (elharo) [inline google-http-client/src/test/java/com/google/api/client/http/HttpResponseTest.java]: you can probably push this (and more) into the try block

File: google-http-client/src/test/java/com/google/api/client/http/HttpResponseTest.java (hunk 8 above)
Comment (egsavage) [reply google-http-client/src/test/java/com/google/api/client/http/HttpResponseTest.java]: This is an existing old test class using JUnit 3 method conventions thus the lack of the @Test annotation. It runs fine as-is.

File: google-http-client/src/test/java/com/google/api/client/http/HttpResponseTest.java [hunk 11]
```diff
@@ -461,6 +462,21 @@ public LowLevelHttpResponse execute() throws IOException {
...
+
+  public void testGetContent_gzipEncoding_finishReadingWithUppercaseContentEncoding() throws IOException {
+    do_testGetContent_gzipEncoding_finishReading("GZIP");
+  }
+
+  public void testGetContent_gzipEncoding_finishReadingWithDifferentDefaultLocaleAndUppercaseContentEncoding() throws IOException {
+    Locale originalDefaultLocale = Locale.getDefault();
+    Locale.setDefault(Locale.JAPAN);
+    do_testGetContent_gzipEncoding_finishReading("GZIP");
+    Locale.setDefault(originalDefaultLocale);
```
Comment (elharo) [inline google-http-client/src/test/java/com/google/api/client/http/HttpResponseTest.java]: this probably should be in a finally block so it's still reset if the test fails

File: google-http-client/src/test/java/com/google/api/client/http/HttpResponseTest.java [hunk 12]
```diff
@@ -461,6 +462,21 @@ public LowLevelHttpResponse execute() throws IOException {
...
+    do_testGetContent_gzipEncoding_finishReading("gzip");
+  }
+
+  public void testGetContent_gzipEncoding_finishReadingWithUppercaseContentEncoding() throws IOException {
+    do_testGetContent_gzipEncoding_finishReading("GZIP");
+  }
+
+  public void testGetContent_gzipEncoding_finishReadingWithDifferentDefaultLocaleAndUppercaseContentEncoding() throws IOException {
+    Locale originalDefaultLocale = Locale.getDefault();
+    Locale.setDefault(Locale.JAPAN);
```
Comment (elharo) [inline google-http-client/src/test/java/com/google/api/client/http/HttpResponseTest.java]: Try Turkish instead:
```
Locale turkish = Locale.forLanguageTag("tr-TR");
```

That's the one common language where i and I do not case like they do in English.

Comment (egsavage) [reply google-http-client/src/test/java/com/google/api/client/http/HttpResponseTest.java]: I switched it to Turkish, but JAPAN in the existing code would have given an exception without the locale specification in the implementation.
